platform :ios, '10.1'

target 'demoapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoapp

#  pod 'VGSCollectSDK'
  pod 'VGSCollectSDK', :path => "../"
  pod 'VGSCollectSDK/CardScan', :path => "../"
  pod 'VGSCollectSDK/CardIO', :path => "../"

end

target 'demoappTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'demoappUITests' do
  inherit! :search_paths
  # Pods for testing
end
