source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.5'

target 'demoapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoapp

#  pod 'VGSCollectSDK'
  pod 'VGSCollectSDK', :path => "../"
  pod 'VGSCollectSDK/CardIO', :path => "../"
  pod 'VGSCollectSDK/BlinkCard', :path => "../"


end

target 'demoappTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'demoappUITests' do
  inherit! :search_paths
  # Pods for testing
end
