source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.5'

abstract_target 'demoappPods' do
  use_frameworks!

  pod 'VGSCollectSDK', :path => "../"
  pod 'VGSCollectSDK/CardIO', :path => "../"
  pod 'VGSCollectSDK/BlinkCard', :path => "../"

  target 'demoapp' do
  end

  target 'demoappTests' do
    inherit! :search_paths
  end

  target 'demoappUITests' do
    inherit! :complete
  end
end
