####################
# Comments
# 1. pods should be installed/updated
# 2. jazzy command should be running form framework root dir
####################
#names
module: VGSCollectSDK
title: VGSCollectSDK
author: Very Good Security
author_url: https://verygoodsecurity.com
github_url: https://github.com/verygoodsecurity/vgs-collect-ios
github_file_prefix: https://github.com/verygoodsecurity/vgs-collect-ios/tree/master
readme: README.md
#output folder
output: docs
#path to project
framework_root: ../
sdk: iphonesimulator
#settings
clean: true
objc: false
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
exclude:
    Sources/VGSCollectSDK/Core/Utils.swift
custom_categories:
- name: UI Elements
  children:
  - VGSTextField
  - VGSCardTextField
  - VGSExpDateTextField
  - VGSTextFieldDelegate
  - VGSConfiguration
  - FieldType
  - SwiftLuhn
- name: Card Scan
  children:
  - VGSCardIOScanController
  - VGSCardIOScanControllerDelegate
  - CradIODataType
- name: File Picker
  children:
  - VGSFilePickerController
  - VGSFilePickerConfiguration
  - VGSFilePickerControllerDelegate
  - VGSFileSource
  - VGSFileInfo
- name: Observe State and Send Data
  children:
  - VGSCollect
  - Environment
  - State
  - SSNState
  - CardState
  - VGSResponse
  - HTTPMethod
  - HTTPHeaders
- name: Payment Cards
  children:
  - VGSPaymentCards
  - VGSPaymentCardModel
  - VGSUnknownPaymentCardModel
- name: Validation Rules
  children:
  - VGSValidationRuleSet
  - VGSValidationRuleLength
  - VGSValidationRuleLengthMatch
  - VGSValidationRulePattern
  - VGSValidationRulePaymentCard
  - VGSValidationRuleLuhnCheck
  - VGSValidationRuleCardExpirationDate
  - CheckSumAlgorithmType
  - CardExpDateFormat
- name: Errors
  children:
  - VGSError
  - VGSErrorType
  - VGSCollectSDKErrorDomain
  - VGSValidationError
  - VGSValidationErrorType
- name: Error Keys
  children:
  - VGSSDKErrorInputDataIsNotValid
  - VGSSDKErrorInputDataRequired
  - VGSSDKErrorInputDataRequiredValid
  - VGSSDKErrorFileNotFound
  - VGSSDKErrorFileTypeNotSupported
  - VGSSDKErrorFileSizeExceedsTheLimit
  - VGSSDKErrorSourceNotAvailable
  - VGSSDKErrorUnexpectedResponseDataFormat
