####################
# Comments
# 1. pods should be installed/updated
# 2. jazzy command should be running form framework root dir
####################
#names
module: VGSFramework
title: VGSCollectSDK
author: Very Good Security
author_url: https://verygoodsecurity.com
github_url: https://github.com/verygoodsecurity/vgs-collect-ios
github_file_prefix: https://github.com/verygoodsecurity/vgs-collect-ios/tree/dev/framework
readme: ../README.md
#output folder
output: ../docs
#path to project
framework_root: framework/
sdk: iphonesimulator
#settings
clean: true
objc: false
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
exclude:
    Sources/VGSFramework/Core/Utils.swift
