disabled_rules: # rule identifiers to exclude from running  
  - trailing_whitespace
  - shorthand_operator
  - unused_setter_value
  - cyclomatic_complexity
  - function_body_length
  - notification_center_detachment
identifier_name:
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
line_length: 180
type_body_length: 400 
reporter: "xcode"
excluded: # paths to ignore during linting. Takes precedence over `included`. 
  - Pods