platform :ios, '12.0'

target 'framework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  target 'frameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
